timeout: 1800s
logsBucket: "gs://${_ARTIFACT_BUCKET_NAME}/cloudbuild-logs/app-${_SERVICE_NAME}-push-request-trigger"
options:
  machineType: 'E2_HIGHCPU_8'
steps:
  - id: 'build'
    name: "${_GAR_BUILDER_URL}/helm"
    entrypoint: bash
    args:
      - "-c"
      - |
        skaffold build -p dev --interactive=false --file-output=/workspace/artifacts.json

  - id: "Cloud Deploy Release"
    name: "google/cloud-sdk"
    entrypoint: bash
    args:
      - "-c"
      - |
        gcloud deploy releases create "${REPO_NAME}--${SHORT_SHA}" \
          --project=devstream-services \
          --region=us-east4 \
          --delivery-pipeline=${REPO_NAME} \
          --gcs-source-staging-dir=gs://devstream-application-pipeline_clouddeploy/source \
          --build-artifacts=/workspace/artifacts.json
